config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  #===================================================
  # Root path
  root 'static_pages#home'
  # Redirect root path
  #root to: redirect('/ja/home')


  #===================================================
  # Static pages
  match '/home', to: 'static_pages#home', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/ceo_message', to: 'static_pages#ceo_message', via: 'get'
  match '/organizer', to: 'static_pages#organizer', via: 'get'
  match '/media', to: 'static_pages#media', via: 'get'
  match '/search_media_article', to: 'static_pages#search_media_article', via: 'get'
  match '/our_sponsors', to: 'static_pages#our_sponsors', via: 'get'
  match '/contact_us', to: 'static_pages#contact_us', via: 'get'
  # Events
  match '/event_list', to: 'static_pages#event_list', via: 'get'
  match '/event_detail', to: 'static_pages#event_detail', via: 'get'
  match '/register_event_form', to: 'static_pages#register_event_form', via: 'post'
  match '/register_event_user', to: 'static_pages#register_event_user', via: 'post'
  match '/deregister_event', to: 'static_pages#deregister_event', via: 'post'
  match '/deregister_event_confirm', to: 'static_pages#deregister_event_confirm', via: 'get'


  #===================================================
  # For authentication
  devise_for :users, controllers: {
    #omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # User page
  resources :users do
    collection do
      get :privacy_policy
    end
  end


  #===================================================
  # Staff only

  # Prefix 'admin'
  # Uncommend and use if need for future
  # https://makandracards.com/makandra/38773-rails-route-namespacing-in-different-flavors
  #scope path: 'admin' do

    resources :accounts

    resources :broadcasts do
      collection do
        get 'sent_list'
      end
      member do
        get 'show_sent'
        get :find_members
        get :search
        get :send_email
        get :broadcast_member_list
        post :add_emails
        post :delete_broadcast_member
        post :update_include_all_flg
        post :update_broadcast_member
        post :update_birth_month
        post :update_event_id
        post :update_include_gtic_flg
      end
    end

    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :contacts do
      member do
        post 'update_response_completed'
      end
    end

    resources :events do
      collection do
        get :download
        get :search
        get :statistics
      end
      member do
        get :registed
        get :update_registed_member
        get :participants
        get :update_participants
        get :dotasan
        get :declined
        get :dotacan
        get :no_show
        get :waiting
        get :add_presenter
        get :add_as_presenter
        get :search_member
        get :statistics
        get :account
        get 'serve_file'
        get 'check_in'
        post :change_status
        post :change_role
        post :destroy_relationship
        post :switch_black_list_flg
        post :update_birthday
        post :create_member
        post 'upload_file'
        post 'set_bkg_image'
      end
    end

    resources :event_categories, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :images do
      collection do
        get :serve
      end
    end

    resources :media_articles do
      member do
        post :delete_file
        get :serve_file
      end
    end

    resources :members do
      collection do
        get :azsa_list
        get :no_show_list
        get :black_list
        get :category
        get :count
        get :search
        post :fill_alphabet_from_kanji_name
      end
      member do
        post 'upload_profile_picture'
      end
    end

    resources :places, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :presentations, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :relationships, only: [:create, :edit, :update, :destroy]
    resources :registers
    resources 'sponsors' do
      member do
        post 'upload_logo_image'
      end
    end
    resources :staffs

  #end # end of scope (prefix)

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # reCAPTCHA
  prepend_before_action :check_captcha, only: [:register_event]


  def home
    # Get new events
    @events = Event.where('start_time > ?', DateTime.now).where(is_public: true).order("start_time DESC")

    # Get one media article
    @media_articles = MediaArticle.where('date > ?', DateTime.now - 30*3).limit(3).order(date: :DESC) # now - days
  end

  def about
    @events = Event.all.order("start_time DESC")
  end

  def event_list
    # For search
    if params[:keyword]
      @events = get_search_event(params[:keyword])

    # Default: show events in a year
    else
      @start_date = Event.order("start_time ASC").first.start_time.beginning_of_year
      @last_date = Event.order("start_time ASC").last.start_time.end_of_year
      if params[:year].present?
        year = Date.parse(params[:year])
        base = Event.where(start_time: year.beginning_of_year..year.end_of_year).group(:start_time)
      else
        base = Event.where(start_time: @last_date.beginning_of_year..@last_date.end_of_year).group(:start_time)
      end
      @events = base.where(is_public: true).order("start_time DESC")
    end

    if @events
      @events = @events.where(is_public: true)
    else
      redirect_to event_list_path
    end
  end

  def event_detail
    if not params[:event_id]
      redirect_to root_path, notice: "Not validate url."
      return
    end
    @event = Event.find(params[:event_id])

    # Count up view
    @event.update(views: @event.views + 1)

    redirect_to root_path, notice: "Not public event." if not @event.is_public

    @is_expired_event =  isExpiredEvent(@event.start_time)

    @presentations = @event.presentations.order("created_at desc")
    if current_user
      relationship = @event.relationships.find_by_member_id(current_user.member_id)
      @is_registered = true if relationship and relationship.status == 2
    else
      @is_registered = params[:is_registered] if params[:is_registered]
    end

    @sponsors = Sponsor.order(:is_end)

    @member = member_params ? Member.new(member_params) : Member.new
  end

  def register_event(member)
    validateEventId(params[:event_id])
    event = Event.find(params[:event_id])

    # Check time
    if isExpiredEvent(event.start_time)
      redirect_to event_detail_path(event_id: event.id), notice: "今は参加登録できません。GTICスタッフに直接連絡お願いします。Cannot register now. Please contact to GTIC staff directry."
      return
    end

    # Find if member already registered
    relationship = event.relationships.find_by_member_id(member.id)
    # If member not regitered
    if relationship
      relationship.update(status: 2)
    else
      Relationship.new(member_id: member.id, event_id: event.id, status: 2).save
    end

    # Send register confirm mail
    NoReplyMailer.registration_confirmation(event, member).deliver
    redirect_to event_detail_path(event_id: event.id, is_registered: true, anchor: 'registration'), flash: { success: "Successfully registered!" }
  end

  def register_event_form
    member = Member.from_registration(member_params)
    register_event(member)
  end

  def register_event_user
    user = User.find(current_user.id)
    member = user.member
    if not member
      redirect_to edit_user_path(user), flash: { notice: "ユーザー情報をご記入ください。Please fill your information." }
      return
    end
    register_event(member)
  end

  def deregister_event
    validateEventId(params[:event_id])
    event = Event.find(params[:event_id])

    # Check time
    if isExpiredEvent(event.start_time)
      redirect_to root_path, notice: "今はキャンセルできません。GTICスタッフに直接連絡お願いします。Cannot deregister now. Please contact to GTIC staff directry."
      return
    end

    # get member
    if not params[:member_id]
      redirect_to root_path, notice: "Not validate url."
      return
    end
    member_id = verify_string_from_hash(params[:member_id])
    member = Member.find(member_id)
    if not member
      redirect_to root_path, notice: "Not validate url."
      return
    end

    # Find member already registered
    relationship = event.relationships.find_by_member_id(member.id)
    if relationship.blank?
      redirect_to root_path, notice: "Not registerd yet."
    else
      if relationship.status == 4
        redirect_to event_detail_path(event_id: event.id), notice: "すでにキャンセルしています。Already deregistered the event."
      elsif relationship.status == 2
        relationship.update(status: 4)
        # Send cancel confirm mail
        NoReplyMailer.deregistration_confirmation(event, member).deliver
        redirect_to event_detail_path(event_id: event.id), notice: "参加登録をキャンセルしました。Successfully deregistered the event."
      end
    end
  end

  def deregister_event_confirm
  end

  def organizer
    @access_token = get_app_access_token
    @organizers = Staff.order(is_active: :desc)
  end

  def media
    @media_articles = MediaArticle.paginate(page: params[:page], per_page: 9).order(date: :desc)
  end

  def search_media_article
    @media_articles = get_search_media_article(params[:keyword])
    if @media_articles
      @is_search = true
      respond_to :js
    else
      redirect_to media_path
    end
  end

  def our_sponsors
    @sponsors = Sponsor.where(is_end: false)
    @sponsors_end = Sponsor.where(is_end: true)
  end

  def contact_us
    @contact = contact_params ? Contact.new(contact_params) : @contact = Contact.new
    if params[:after_submit]
      @after_submit = true
    end
  end


  private
    def contact_params
      params.fetch(:contact, {}).permit(
        :name, :category_id, :affiliation, :title, :email,
        :subject, :body
      )
    end

    def member_params
      params.fetch(:member, {}).permit(
        :first_name, :last_name, :first_name_alphabet, :last_name_alphabet,
        :category_id, :affiliation, :title, :email
      )
    end


    def isExpiredEvent(start_time, hour=-7)
      return DateTime.now > start_time+60*60*hour # Default 7h before start
    end

    def validateEventId(event_id)
      if not event_id or not Event.find(event_id)
        redirect_to root_path, notice: "Not validate url."
        return
      end
    end

    # reCAPTCHA
    def check_captcha
      unless verify_recaptcha
        redirect_to event_detail_path(event_id: params[:event_id], member: member_params, anchor: 'registration')
      end
    end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def select_locale
    case params[:locale]
    when nil, 'ja'
      locale_now = ['Japanese', 'ja']
      locale_array = [ ['English', 'en'] ]
    when 'en'
      locale_now = ['English', 'en']
      locale_array = [ ['Japanese', 'ja'] ]
    end

    content_tag(:li, class: "nav-item dropdown") {
      concat content_tag(:a, href: '#', id: 'dropdowmLocale',class: "nav-link dropdown-toggle py-0", data: {'bs-toggle': "dropdown"}, 'aria-haspopup': "true", 'aria-expanded': "false") {
        content_tag(:b, locale_now[0], class: "caret")
      }
      concat content_tag(:div, class: "dropdown-menu", id: 'dropdowmLocale') {
        locale_array.each do |locale|
          concat link_to(locale[0], {locale: locale[1]}, class: 'dropdown-item')
        end
      }
    }
  end

end

app/views/static_pages/_events.html.erb
<% @events.each do |event| %>

  <div class="card" data-aos="fade-up">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-4">
          <%= image_tag serve_file_event_path(id: event.id), class: 'img-fluid' if event.header_data %>
        </div>

        <div class="col-sm-7">
          <h5 class="card-title">
            <%= link_to event_detail_path(event_id: event.id) do %>
              <%= event.name + ' ' + event.event_category.name %>
            <% end %>
          </h5>

          <%= l(event.start_time) %>
          <%= '@' + event.place.name %>

          <% event.presentations.sort_by{|e| e[:id]}.each do |presentation| %>
            <li>
              <mark><%= presentation.title %></mark><br>
                <% presentation.presenters.each do |presenter| %>
                  <strong><%= presenter.affiliation %></strong>
                  <%= presenter.title %> <strong><%= presenter.last_name + ' ' + presenter.first_name %></strong> 氏
                <% end %>
            </li>
          <% end %>
        </div>

        <div class="col-sm-1">
          <%= link_to t('detail'), event_detail_path(event_id: event.id), class: 'btn btn-outline-info' %>
          <% relationship = Relationship.where(event_id: event.id, member_id: current_user.member_id).first if current_user %>
          <% if current_user && relationship && relationship.status == 2 %>
            <%= link_to t('already_registered'), nil, class: 'btn btn-outline-success disabled' %>
          <% else %>
            <%= link_to t('register'), event_detail_path(event_id: event.id, anchor: 'registration'), class: 'btn btn-outline-success' %>
          <% end %>
          <%= link_to tag.i('', class: 'fab fa-facebook-f'), "https://facebook.com/"+event.fb_event_id, class: 'btn btn-outline-primary', target: 'blank' if event.fb_event_id.present? %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/static_pages/contact_us.html.erb
<% content_for :title, 'Contact us' %>

<div class="container">
  <h1>お問い合わせ/Contact us</h1>

  <br>

  <% if @after_submit %>
    <h3>正常に送信されました!/Sent success fully!</h3>
  <% else %>
    <%= render 'contacts/form' %>

    <hr>

    <h3>または、ソーシャルアカウントでお問い合わせ / or, contact via social account</h3>
    <%= link_to tag.i(class: 'fab fa-facebook-square')+' facebook', 'https://facebook.com/GTICafe', class: 'btn btn-primary', target: 'blank' %>
  <% end %>

</div>

app/views/static_pages/deregister_event_confirm.html.erb
<h5>イベント参加をキャンセルします。よろしいでようか？Deregister the event. Are you sure?</h5>
<%= link_to t('confirm'), deregister_event_path(event_id: params[:event_id], member_id: params[:member_id]), method: 'post', class: 'btn btn-primary' %>
<%= link_to t('cancel'), event_detail_path(event_id: params[:event_id]), class: 'btn btn-info' %>

app/views/static_pages/event_list.html.erb
<% content_for :title, 'Events' %>

<div class="container">
  <h1>GTIC Events</h1>

  <!-- Search -->
  <%= form_tag event_list_path, method: 'get' do %>
    <div class="row">
      <%= hidden_field_tag 'locale', params[:locale] if params[:locale] %>
      <%= label_tag :keyword, 'イベント検索', class: 'col-form-label col-auto' %>
      <%= text_field_tag :keyword, params[:keyword], class: "form-control col", placeholder: "keyword" %>
      <%= submit_tag 'Search', name: nil, class: 'btn btn-primary col-auto' %>
    </div>
    <div class="row">
      <span class='form-text col-auto'>*企業名、登壇者名、発表タイトル、概要、会場名から検索できます(OR検索：スペースで区切る)</span>
      <span class='form-text col-auto'>*登壇者は漢字もしくは英字名で検索可能。</span>
      <span class='form-text col-auto'>*ヒットしない場合は単語の一部分を入れてください。</span>
    </div>
  <% end %>

  <!-- per year Paginate -->
  <% if @start_date.present? and @last_date.present? %>
    <div class="btn-group btn-group-sm row">
      <% date = @last_date%>
      <% while date >= @start_date do %>
        <%= link_to "#{date.strftime("%Y")}年", event_list_path(year: date.strftime("%Y-%m-%d")),
            class: "btn btn-info col-auto" %>
        <% date = date - 1.year %>
      <% end %>
    </div>
  <% end %>

  <div id="ajax_container">
    <%= render 'events' %>
  </div>

</div>

app/views/static_pages/home.html.erb
<% content_for :title, 'Home' %>

<!-- unheld event -->
<% if @events.count != 0 %>
  <article class="container">
    <h2 class="text-center">-<%= t('new_event') %>-</h2>
    <%= render 'static_pages/events' %>
  </article>
<% end %>


<!-- Carousel -->
<article class="container-fluid w-100 h-100" data-aos="zoom-out">
  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 0"></button>
      <% n = 1 %>
      <% @events.each do |event| %>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= n %>" aria-label="Slide <%= n%>"></button>
        <% n += 1 %>
      <% end %>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= n %>" aria-label="Slide <%= n%>"></button>
      <% n += 1 %>
    </div>

    <div class="carousel-inner">
      <section class="carousel-item active home-carousel home-carousel-bkg">
        <div class="home-carousel-content py-5">
          <%= image_tag 'logo200x200.png', alt: 'GTIC logo 200x200', class: "mx-auto d-block" %>
          <h1><%= t('home.top_message')%></h1>
          <p style="opacity: 0.8; font-size: 1.3em;"><%= t('home.short_about')%></p>
          <div class='text-center'><%= link_to t('home.about'), :about, class: "btn btn-info btn-lg" %></div>
        </div>
      </section>

      <% @events.each do |event| %>
        <style>
          .home-carousel-event-<%= event.id %>::after {
            content: "";
            background-image: url('<%= serve_images_path(id: event.bkg_image_id) if event.bkg_image_id %>');
            background-position: center; /* Center the image */
            background-repeat: no-repeat;
            background-size: cover;
            filter: blur(8px);
            opacity: 0.5;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            position: absolute;
            z-index: -1;
          }
        </style>

        <section class="carousel-item home-carousel home-carousel-event-<%= event.id %>">
          <div class="home-carousel-content py-5">
            <p style="color: red;">New event!</p>
            <h2><%= event.name + ' ' + event.event_category.name %></h2>
            <% event.presentations.sort_by{|e| e[:id]}.each do |presentation| %>
              <li>
                <h3 style='display:inline;'>「<%= presentation.title %>」</h3>
                <% presentation.presenters.each do |presenter| %>
                  <strong><%= presenter.affiliation %></strong> <%= presenter.title %> <strong><%= presenter.last_name + ' ' + presenter.first_name %></strong> 氏
                <% end %>
              </li>
            <% end %>

            <div class="row pt-5">
              <div class="col-auto"><i class="fas fa-calendar" style='font-size: 3em;'></i></div>
              <div class="col-auto">
                <strong>WHEN</strong><br>
                <p><%= l event.start_time, format: :default%></p>
              </div>
            </div>
            <br>

            <div class="row">
              <div class="col-auto"><i class="fas fa-map-marker-alt" style='font-size: 3em;'></i></div>
              <div class="col-auto">
                <strong>WHERE</strong><br>
                <p><%= event.place.name %></p>
              </div>
              <div class="offset-sm-5 col text-end">
                <%= link_to t('detail'), event_detail_path(event_id: event.id), class: 'btn btn-success btn-lg btn-block' %>
              </div>
            </div>

          </div>
        </section>
      <% end %>

      <section class="carousel-item home-carousel home-carousel-success">
        <div class="home-carousel-content py-5">
          <h2 class='py-3'><%= t('home.media_message') %></h2>
          <% @media_articles.each do |media_article| %>
            <h3 style='font-size: 1.3em;'>・<%= media_article.media %>「<%= media_article.title %>」 <strong><%= media_article.member.affiliation %></strong></h3>
          <% end %>
          <p>など<p>
          <h3 class='py-2'>More on <a href="/media">MEDIA ARTICLE PAGE</a></h3>
        </div>
      </section>

    </div><!-- end of carousel-inner -->

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div><!-- end of carousel -->
</article>


<!-- Cards -->
<article class="container" data-aos="fade-up" style="padding: 60px 0;">
  <h2 class="text-center">-<%= t('activities') %>-</h2>

  <div class="text-center">
    <a href="https://www.facebook.com/GTICafe/photos/?ref=page_internal" class="btn btn-secondary"><%= t('home.fb_album') %></a>
  </div>

  <div class="row">
    <section class="col-sm-6 hvr-bounce-in">
      <div class="card" data-aos="fade-up">
        <div class="card-body">
          <h3 class="card-title text-center">
            <i class="fa fa-globe"></i>
            <a href="/about#conference"><%= t('conference') %></a>
          </h3>
          <p class="card-text"><%= t('home.conference_point') %></p>
        </div>
      </div>
    </section>

    <section class="col-sm-6 hvr-bounce-in">
      <div class="card" data-aos="fade-up">
        <div class="card-body">
          <h3 class="card-title text-center">
            <i class="fa fa-link"></i>
            <a href="/about#networking_party"><%= t('networking_party') %></a>
          </h3>
          <p class="card-text"><%= t('home.networking_party_point') %></p>
        </div>
      </div>
    </section>
  </div>

  <div class="row">
    <section class="col-sm-6 hvr-bounce-in">
      <div class="card" data-aos="fade-up">
        <div class="card-body">
          <h3 class="card-title text-center">
            <i class="fa fa-book"></i>
            <a href="/about#workshop"><%= t('chisikinoizumi') %></a>
          </h3>
          <p class="card-text"><%= t('home.chisikinoizumi_point') %></p>
        </div>
      </div>
    </section>

    <section class="col-sm-6 hvr-bounce-in">
      <div class="card" data-aos="fade-up">
        <div class="card-body">
          <h3 class="card-title text-center">
            <i class="fa fa-edit"></i>
            <a href="/about#workshop"><%= t('breakout_session') %></a>
          </h3>
          <p class="card-text"><%= t('home.breakout_session_point') %></p>
        </div>
      </div>
    </section>
  </div>
</article><!-- end of cards -->


<!-- Social -->
<article class="container text-center" data-aos="fade-up">
  <h2 class="text-center">-Connect us-</h2>

  <div class='row'>
    <div class='col-sm-6'>
      <h3>
        Facebook page
        <%= link_to tag.i(class: 'fab fa-facebook-square'), 'https://facebook.com/GTICafe', target: 'blank' %>
      </h3>
      <div class="fb-page py-3" data-href="https://www.facebook.com/GTICafe/" data-tabs="timeline"
          data-width="500" data-height="" data-small-header="false" data-adapt-container-width="true"
          data-hide-cover="false" data-show-facepile="true">
        <blockquote cite="https://www.facebook.com/GTICafe/" class="fb-xfbml-parse-ignore">
          <a href="https://www.facebook.com/GTICafe/">Global Techno Innovation Cafe (GTIC)</a>
        </blockquote>
      </div>
    </div>
    <div class='col-sm-6'>
      <h3>
        Line account
        <a href="https://lin.ee/i6liGlO", target='blank'>
          <img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height='36' border="0">
        </a>
      </h3>
      <div class='py-3'></div>
      <img src="https://qr-official.line.me/sid/M/383emaiy.png">
    </div>
  </div>
</article>

app/views/static_pages/media.html.erb
<% content_for :title, 'Media articles' %>

<div class="container">

  <h1>Media articles</h1>

  <h2>登壇企業の記事</h2>
  <p>過去にGTICイベントに登壇された企業の活躍に関する記事です</p>

  <!-- Search -->
  <%= form_tag '/search_media_article', method: 'get', remote: true, role: "form" do %>
    <div class="row">
      <%= label_tag :keyword, '記事検索', class: 'col-form-label col-auto' %>
      <%= text_field_tag :keyword, params[:keyword], class: "form-control col", placeholder: "keyword" %>
      <%= submit_tag 'Search', :name => nil, class: 'btn btn-primary col-auto' %>
    </div>
    <div class="row">
      <span class='form-text col-auto'>*メディア名、記事名、企業名、登壇者名から検索できます(OR検索：スペースで区切る)</span>
    </div>
  <% end %>

  <div class="row" id="ajax_container">
    <%= render 'media_articles' %>
  </div>

  <div class='py-5'></div>

  <h2>CHIEF ORGANIZER'S ACTIVETY</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Activeties</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <th scope="row">2021/12/15</td>
        <td><%= link_to "	蔵前工業会 第19回蔵前立志セミナー 「誰も正解を知らないニューノーマル時代の生き方」", serve_file_media_article_path(80), target: :blank %></td>
      </tr>
      <tr>
        <th scope="row">2021/07/15</td>
        <td><%= link_to "	Deal Watch 「日本のIPO市場について」", serve_file_media_article_path(70), target: :blank %></td>
      </tr>
      <tr>
        <th scope="row">2015/02/21</td>
        <td><%= link_to "大阪大学 博士課程 超域イノベーション・プログラム", "http://www.cbi.osaka-u.ac.jp/choikijijo/article/school20th/", target: :blank %></td>
      </tr>
      <tr>
        <th scope="row">2014/12/13</td>
        <td><%= link_to "沖縄科学技術大学院大学(OIST)　起業家人材育成プログラム(Entrepreneurial Training Program)", "https://groups.oist.jp/ja/bds/event/2014-entrepreneurial-training-program-day-3", target: :blank %></td>
      </tr>
      <tr>
        <th scope="row">2014/07/09</td>
        <td><%= link_to "BBT大学 資産形成力養成講座 @東京（市ヶ谷） セミナー『元外資系インベストメントバンカーが解説する資産運用の仕組みと本質』", "http://www.ohmae.ac.jp/ex/asset/guide/event/996/http://www.cbi.osaka-u.ac.jp/choikijijo/article/school20th/", target: :blank %></td>
      </tr>
    </tbody>
  </table>


</div>

app/views/static_pages/media.js.erb
$("#ajax_container").html("<%= escape_javascript(render('media_articles')) %>");

app/views/static_pages/our_sponsors.html.erb
<% content_for :title, 'Sponsors' %>

<div class="container">
  <h1>Our Sponsors</h1>
  <p>Companies that support us</p>
  <br>

  <% @sponsors.each do |sponsor| %>
    <div class="row border rounded" data-aos="fade-up" id="<%= sponsor.id %>" style="padding: 30px; margin-bottom: 60px;">
      <div class="col">
        <h2 class="text-center"><%= sponsor.name %></h2>
      </div>
      <div class="w-100"></div>
      <div class="col">
        <%= image_tag "data:#{sponsor.logo_mime_type};base64,#{Base64.strict_encode64(sponsor.logo_data)}",
            alt: sponsor.logo_name, class: 'mx-auto d-block', height: '300' if sponsor.logo_name %>
      </div>
      <div class="w-100"></div>
      <div class="col">
        <h3 class="text-center"><%= sponsor.slogan %></h3>
        <p class="text-center"><%= sponsor.description %></p>
        <p class="text-center"><%= link_to sponsor.website, sponsor.website %></p>
      </div>
    </div>

  <% end %>

  <div class="row">
    <% @sponsors_end.each do |sponsor| %>
      <div class="col-sm-3" data-aos="fade-up" style="margin-right: 10px; opacity: 0.5;">
        <h5 class="text-center"><%= sponsor.name %></h5>
        <%= image_tag "data:#{sponsor.logo_mime_type};base64,#{Base64.strict_encode64(sponsor.logo_data)}",
            alt: sponsor.logo_name, class: 'card-img-bottom' if sponsor.logo_name %>
      </div>
    <% end %>
  </div>

</div>

app/views/static_pages/presenter.html.erb
<div class="container-fluid">
  <h1>GTIC PRESENTER</h1>

  <!-- Search -->
  <%= form_tag '/search_event', method: 'get', remote: true, class: "form-inline", role: "form" do %>
     <div class="form-group">
      <strong>イベント検索　</strong>
      <span>Keyword: </span>
      <%= text_field_tag :keyword, params[:keyword], class: "form-control", placeholder: "keyword" %>
    </div>
    <%= submit_tag 'Search', :name => nil, class: 'btn btn-primary' %>
    アルファベットによる検索もOK（ひらがな、カタカナは未対応）
  <% end %>

  <!-- per year Paginate -->
  <% if @start_date.present? and @last_date.present? %>
    <div class="btn-group">
      <% date = @last_date%>
      <% while date >= @start_date do %>
        <%= link_to "#{date.strftime("%Y")}年", presenter_path(:year => date.strftime("%Y-%m-%d")), class: "btn btn-info", remote: true %>
        <% date = date - 1.year %>
      <% end %>
    </div>
  <% end %>

  <div id="ajax_container">
    <%= render 'events' %>
  </div>

</div>