config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  #===================================================
  # Root path
  root 'static_pages#home'
  # Redirect root path
  #root to: redirect('/ja/home')


  #===================================================
  # Static pages
  match '/home', to: 'static_pages#home', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/ceo_message', to: 'static_pages#ceo_message', via: 'get'
  match '/organizer', to: 'static_pages#organizer', via: 'get'
  match '/media', to: 'static_pages#media', via: 'get'
  match '/search_media_article', to: 'static_pages#search_media_article', via: 'get'
  match '/our_sponsors', to: 'static_pages#our_sponsors', via: 'get'
  match '/contact_us', to: 'static_pages#contact_us', via: 'get'
  # Events
  match '/event_list', to: 'static_pages#event_list', via: 'get'
  match '/event_detail', to: 'static_pages#event_detail', via: 'get'
  match '/register_event_form', to: 'static_pages#register_event_form', via: 'post'
  match '/register_event_user', to: 'static_pages#register_event_user', via: 'post'
  match '/deregister_event', to: 'static_pages#deregister_event', via: 'post'
  match '/deregister_event_confirm', to: 'static_pages#deregister_event_confirm', via: 'get'


  #===================================================
  # For authentication
  devise_for :users, controllers: {
    #omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # User page
  resources :users do
    collection do
      get :privacy_policy
    end
  end


  #===================================================
  # Staff only

  # Prefix 'admin'
  # Uncommend and use if need for future
  # https://makandracards.com/makandra/38773-rails-route-namespacing-in-different-flavors
  #scope path: 'admin' do

    resources :accounts

    resources :broadcasts do
      collection do
        get 'sent_list'
      end
      member do
        get 'show_sent'
        get :find_members
        get :search
        get :send_email
        get :broadcast_member_list
        post :add_emails
        post :delete_broadcast_member
        post :update_include_all_flg
        post :update_broadcast_member
        post :update_birth_month
        post :update_event_id
        post :update_include_gtic_flg
      end
    end

    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :contacts do
      member do
        post 'update_response_completed'
      end
    end

    resources :events do
      collection do
        get :download
        get :search
        get :statistics
      end
      member do
        get :registed
        get :update_registed_member
        get :participants
        get :update_participants
        get :dotasan
        get :declined
        get :dotacan
        get :no_show
        get :waiting
        get :add_presenter
        get :add_as_presenter
        get :search_member
        get :statistics
        get :account
        get 'serve_file'
        get 'check_in'
        post :change_status
        post :change_role
        post :destroy_relationship
        post :switch_black_list_flg
        post :update_birthday
        post :create_member
        post 'upload_file'
        post 'set_bkg_image'
      end
    end

    resources :event_categories, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :images do
      collection do
        get :serve
      end
    end

    resources :media_articles do
      member do
        post :delete_file
        get :serve_file
      end
    end

    resources :members do
      collection do
        get :azsa_list
        get :no_show_list
        get :black_list
        get :category
        get :count
        get :search
        post :fill_alphabet_from_kanji_name
      end
      member do
        post 'upload_profile_picture'
      end
    end

    resources :places, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :presentations, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :relationships, only: [:create, :edit, :update, :destroy]
    resources :registers
    resources 'sponsors' do
      member do
        post 'upload_logo_image'
      end
    end
    resources :staffs

  #end # end of scope (prefix)

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence:true, length: { maximum: 50 }
  has_many :relationships, foreign_key: "event_id", dependent: :destroy
  has_many :members, through: :relationships, source: :member
  has_many :maybe_members, -> { where "status = 1"}, through: :relationships, source: :member
  has_many :registed_members, -> { where "status = 2"}, through: :relationships, source: :member
  has_many :dotasan, -> {where "status = 6"}, through: :relationships, source: :member
  has_many :declined_members, -> {where "status = 0 or status = 4"}, through: :relationships, source: :member
  has_many :dotacan, -> {where "status = 7"}, through: :relationships, source: :member
  has_many :no_show, -> {where "status = 5"}, through: :relationships, source: :member
  has_many :invited_members, -> {where "status = 1"}, through: :relationships, source: :member # 未定者

  # presenter, panelist, moderator
  has_many :presenters, -> {where :relationships => {presentation_role: 1..3}}, through: :relationships, source: :member
  has_many :search_presenter, ->(keyword) { where :relationships => {presentation_role: 1..3}}, through: :relationships, source: :member
  has_many :guests, -> {where :relationships => {guest_flg: true}}, through: :relationships, source: :member
  has_many :participants, -> { where "status = 3 or status = 6"}, through: :relationships, source: :member

  has_many :presentationships, foreign_key: "event_id", dependent: :destroy
  has_many :presentations, -> { distinct }, through: :presentationships, source: :presentation
  has_many :registers, foreign_key: "event_id", dependent: :destroy
  has_many :accounts, through: :registers, source: :account

  belongs_to :event_category
  belongs_to :place
#  has_many :presentations, foreign_key: "event_id", dependent: :destroy


  # =========================================================
  # scopes
  scope :year_between, ->(year) { where(:start_time => Date.parse(year).beginning_of_year..Date.parse(year).end_of_year) }

end

app/helpers/events_helper.rb
module EventsHelper

  def relationship(participant)
    Relationship.where(participated_id: @event.id).find_by_participant_id(participant.id)
  end

  def check_event_flg(participant)
    presenter_flg = Relationship.where(participated_id: @event.id).find_by_participant_id(participant.id).presenter_flg
    if presenter_flg == true
      "o"
    else
      "x"
    end
  end

  def show_status(member)
    relationship = @event.relationships.find_by_member_id(member.id)
    case relationship.status
    when 0
      "欠席" #facebook参照
    when 1
      "未定" #facebook参照, dont use it sice 2021/4/6
    when 2
      "参加予定"
    when 3
      "出席"
    when 4
      "欠席" #手入力参照, 本当に欠席した人
    when 5
      "No-show"
    else
      "待機"
    end
  end

  def select_status(member)
    relation = member.relationships.find_by_event_id(@event)
    status_code = relation.present? ? relation.status : nil
    case status_code
    when 2
      status_now = ["参加予定", 2]
      status_array = [["出席", 3], ["ドタ参", 6], ["欠席", 4], ["ドタキャン", 7], ["No-show", 5]]
    when 3
      status_now = ["出席", 3]
      status_array = [["参加予定", 2], ["ドタ参", 6], ["欠席", 4], ["ドタキャン", 7], ["No-show", 5]]
    when 0, 4
      status_now = ["欠席", 4]
      status_array = [["参加予定", 2], ["出席", 3], ["ドタ参", 6], ["ドタキャン", 7], ["No-show", 5]]
    when 5
      status_now = ["No-show", 5]
      status_array = [["参加予定", 2], ["出席", 3], ["ドタ参", 6], ["欠席", 4], ["ドタキャン", 7]]
    when 6
      status_now = ["ドタ参", 6]
      status_array = [["参加予定", 2], ["出席", 3], ["欠席", 4], ["ドタキャン", 7], ["No-show", 5]]
    when 7
      status_now = ["ドタキャン", 7]
      status_array = [["参加予定", 2], ["出席", 3], ["ドタ参", 6], ["欠席", 4], ["No-show", 5]]
    end

    case status_code
    when 1, nil
      link_to("追加", change_status_event_path(member_id: member.id, direction: 2, referer: @referer), method: :post, class: "btn btn-xs btn-secondary", remote: true)
    else
      content_tag(:div, class: "btn-group") {
        concat content_tag(:button, class: "btn dropdown-toggle btn-info btn-xs", data: {toggle: "dropdown"}) {
          content_tag( :span, status_now[0], class: "caret")
        }
        concat content_tag(:div, class: "dropdown-menu") {
          status_array.each do |status|
            concat link_to(status[0], change_status_event_path(member_id: member.id, direction: status[1], referer: @referer), class: 'dropdown-item', method: 'post', remote: true)
          end
          concat link_to("Delete", destroy_relationship_event_path(member_id: member.id), class: 'dropdown-item', method: :post, remote: true)
        }
      }
    end
  end

  def select_role(member,event)
    record = member.relationships.find_by_event_id(event.id)
    gtic_flg = member.gtic_flg
    presentation_role = record.presentation_role

    # Role メニュー
    if presentation_role == 1
      title = ["Presenter","GTIC" ,"Panelist", "Moderator", "Guest", "過去登壇者", "参加者"]
      role = [nil, "gtic", "panelist", "moderator", "guest", "past_presenter", "participant"]
    elsif presentation_role == 2
      title = ["Panelist", "GTIC", "Presenter", "Moderator", "Guest", "過去登壇者", "参加者"]
      role = [nil, "gtic", "presenter", "moderator", "guest", "past_presenter", "participant"]
    elsif presentation_role == 3
      title = ["Moderator", "GTIC", "Presenter", "Panelist", "Guest", "過去登壇者", "参加者"]
      role = [nil, "gtic", "presenter", "panelist","guest", "past_presenter", "participant"]
    elsif presentation_role == 4
      title = ["Guest", "GTIC", "Presenter", "Panelist", "Moderator", "過去登壇者", "参加者"]
      role = [nil, "gtic", "presenter", "panelist", "moderator", "past_presenter", "participant"]
    elsif presentation_role == 5
      title = ["過去登壇者", "GTIC", "Presenter", "Panelist", "Moderator", "Guest", "参加者"]
      role = [nil, "gtic", "presenter", "panelist", "moderator", "guest", "participant"]
    elsif gtic_flg
      title = ["GTIC", "Presenter", "Panelist", "Moderator", "Guest", "過去登壇者", "参加者"]
      role = [nil, "presenter", "panelist", "moderator", "guest", "past_presenter", "participant"]
    else
      title = ["参加者", "GTIC", "Presenter", "Panelist", "Moderator", "Guest", "過去登壇者"]
      role = [nil, "gtic", "presenter", "panelist", "moderator", "guest", "past_presenter"]
    end
    content_tag(:div, class: "btn-group") {
      concat content_tag(:button, "#{title[0]} #{content_tag(:span, '', class: 'caret')}".html_safe, class: "dropdown-toggle btn btn-xs btn-info", data: {toggle: "dropdown"})
      concat content_tag(:div, class: "dropdown-menu", role: "menu", 'aria-labelledby': "dLabel") {
        concat link_to(title[1], change_role_event_path(member_id: member.id, role: role[1], referer: @referer), class: 'dropdown-item', method: 'post', remote: true)
        concat link_to(title[2], change_role_event_path(member_id: member.id, role: role[2], referer: @referer), class: 'dropdown-item', method: 'post', remote: true)
        concat link_to(title[3], change_role_event_path(member_id: member.id, role: role[3], referer: @referer), class: 'dropdown-item', method: 'post', remote: true)
        concat link_to(title[4], change_role_event_path(member_id: member.id, role: role[4], referer: @referer), class: 'dropdown-item', method: 'post', remote: true)
        concat link_to(title[5], change_role_event_path(member_id: member.id, role: role[5], referer: @referer), class: 'dropdown-item', method: 'post', remote: true)
        concat link_to(title[6], change_role_event_path(member_id: member.id, role: role[6], referer: @referer), class: 'dropdown-item', method: 'post', remote: true)
      }
    }
  end

  def show_fee(member, event)
    record = member.relationships.find_by_event_id(event.id)
    presentation_role = record.presentation_role
    gtic_flg = member.gtic_flg
    past_presenter_flg = member.past_presenter_flg

    # Birthday
    if member.birthday
      if member.birthday.strftime("%m") == event.start_time.strftime("%m")
        birthday_flg = true
      else
        birthday_flg = false
      end
    else
      birthday_flg = false
    end
    fee = event.fee || 0

    if birthday_flg
      fee -= 1000
    end

    student_flg = member.category_id == 10 ? true : false
    if student_flg
      fee -= 2000
    end

    if past_presenter_flg
      fee -= 2000
    end

    if member.contributor_flg
      fee -= 1000
    end

    if ((0 < presentation_role) && (presentation_role < 5) || gtic_flg)
      fee = 0
    end
    fee
  end

  def select_birthday(member, event)
    if member.birthday
      if member.birthday.strftime("%m") == event.start_time.strftime("%m")
        link_to update_birthday_event_path(member_id: member.id, referer: @referer), method: "post", remote: true, class:"btn btn-xs" do
          content_tag(:span, "", class:"fa fa-check")
        end
      else
        content_tag :button, disabled: "disabled", class: "btn btn-default btn-xs" do
          content_tag(:span, "", class:"fa fa-square")
        end
      end
    else
      link_to update_birthday_event_path(member_id: member.id, referer: @referer, birthday: true), method: "post", remote: true, class:"btn btn-xs" do
        content_tag(:span, "", class:"fa fa-square")
      end
    end
  end

  def select_black_list(member, event)
    if member.black_list_flg
      link_to switch_black_list_flg_event_path(member_id: member.id, referer: @referer), method: "post", remote: true, class:"btn btn-xs" do
        content_tag(:span, "", class:"fa fa-check")
      end
    else
      link_to switch_black_list_flg_event_path(member_id: member.id, referer: @referer, black_list_flg: true), method: "post", remote: true, class:"btn btn-xs" do
        content_tag(:span, "", class:"fa fa-square")
      end
    end
  end

  def show_note(member, event) # Not use since 2019-04-13
    relationship = member.relationships.find_by_event_id(event.id)
    if relationship.note
      link_to edit_relationship_path(relationship.id), class: "btn btn-secondary btn-xs", remote: true do
        content_tag :span, "", class: "fa fa-check note", data: {content: relationship.note }
      end
    else
      link_to edit_relationship_path(relationship.id), class: "btn btn-default btn-xs", remote: true do
        content_tag :span, "", class: "fa fa-square"
      end
    end
  end

end

app/views/events/_events.html.erb
<table class="table table-bordered table-sm" style="font-size: 13px;">
  <thead>
    <tr>
      <th width="5%">累計</th>
      <th width="5%">イベント名</th>
      <th width="5%">開催日</th>
      <th width="5%">分類</th>
      <th width="10%">会場</th>
      <th width="5%">出席者数</th>
      <th width="15%">プレゼンター</th>
      <th width="20%">タイトル</th>
      <th>概要</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>

      <tr>
        <td rowspan="<%= event.presentations.count %>"><%= "第#{event.cumulative_number}回" %></td>
        <td rowspan="<%= event.presentations.count %>"><%= link_to event.name, event_path(event.id) %> (<%= event.is_public ? "公開" : "非公開" %>)</td>
        <td rowspan="<%= event.presentations.count %>"><%= l event.start_time %></td>
        <td rowspan="<%= event.presentations.count %>"><%= event.event_category.name %></td>
        <td rowspan="<%= event.presentations.count %>"><%= event.place.name %></td>
        <td rowspan="<%= event.presentations.count %>"><%= event.participants.count %>名</td>
        <% event.presentations.each_with_index do |presentation, index| %>
          <% if index >= 1 %>
            </tr>
            <tr>
          <% end %>
          <td>
            <% presentation.presenters.each do |presenter| %>
              <strong><%= presenter.affiliation %></strong><br>
              <%= presenter.title %> <%= presenter.last_name + ' ' + presenter.first_name + ' 氏' %>
            <% end %>
          </td>
          <td><%= presentation.title %></td>
          <td><%= presentation.abstract %></td>
        <% end %>
      </tr>

    <% end %>

  </tbody>
</table>

app/views/events/_fb_event_content.html.erb
<%= @event.name %><br>
<%= '会場: ' + @event.place.name %><br>
<br>
「分野・年齢・国籍関係なく繋がり、よりオープンに、よりグローバルに、よりイノベイティブに、ベンチャー、起業、スタートアップ、イノベーションを考えよう！」<br>
("Let's exchange your opinions of start-up, entrepreneurship, innovation beyond field, age, nationality. --- more open, more global, more innovative!!")<br>
GTICは日本におけるスタートアップ、投資家のマッチングの場や、企業・大学・研究機関との提携なども含めた、リアルビジネス創造の場を提供しております。<br>
<br>
＜当日スケジュール＞<br>
・<%= (@event.start_time-30*60).strftime("%H:%M") %>-会場オープン、受付開始(Open)<br>
(<%= (@event.start_time-30*60).strftime("%H:%M") %>までは鍵が開いておらず部屋へ入ることができませんので、時間になるまでは同ビルの一階にてお待ちください。)<br>
・<%= (@event.start_time).strftime("%H:%M") %>-<%= (@event.start_time+5*60).strftime("%H:%M") %> Opening Speech<br>
<br>
<% @event.presentations.each_with_index do |presentation, index| %>
  ・<%= (presentation.start_time).strftime("%H:%M") if presentation.start_time %>-<%= (presentation.end_time).strftime("%H:%M") if presentation.start_time %><br>
  ①Presentation　その<%= index+1%><br>
  <% presentation.presenters.each do |presenter| %>
    <%= presenter.affiliation %><br>
    <%= presenter.title + ' ' + presenter.last_name + ' ' + presenter.first_name %><br>
    略歴: <%= presenter.biography %><br>
  <% end %>
  ■プレゼン題名<br>
  <%= presentation.title %><br>
  ■プレゼン概要<br>
  <%= presentation.abstract %><br>
  <br>
<% end %>

・<%= (@event.end_time-100*60).strftime("%H:%M") %>-<%= (@event.end_time-90*60).strftime("%H:%M") %>アンケート記入　(Fill out a questionnaire)<br>
・<%= (@event.end_time-90*60).strftime("%H:%M") %>- : 懇親会　Networking party --- drink, eat, and talk!!<br>
※Elevator Pitch: Birthday attenders, First-time attenders<br>
※Muslims are welcome ! : We prepare Halal foods.<br>
・<%= (@event.end_time).strftime("%H:%M") %>: 集合写真、終了（Taking pictures, Closing）<br>
<br>
----------------------------------------<br>
＜GTICへの参加方法＞<br>
GTICホームページのイベントページ<br>
https://gtic.jp<%= event_detail_path(event_id: @event.id, anchor: 'registration') %><br>
にて参加登録をしてください。
また、Facebook上で繋がりを広めるために、このイベントページ上方の「参加予定」ボタンを押して下さい。<br>
----------------------------------------<br>
<br>
〈会場〉<br>
場所: <%= @event.place.name %><br>
住所: <%= @event.place.address %><br>
Google Map: https://www.google.com/maps/search/?api=1&query=<%= @event.place.latitude %>,<%= @event.place.longitude %><br>
Access: <%= @event.place.how_to_go %>
----------------------------------------<br>
＜会費 fee＞<br>
・一般 business person 及び、仕事を持っていらっしゃる社会人学生: 5,000円<br>
・フルタイムの学生 full time student: 3,000円（学生証をお持ち下さい。Bring your student ID.）<br>
・GTIC開催日と同じ月の誕生日の方は1000円割引です。（上記学生割引との併用OKです。）　誕生日がわかる運転免許証や、学生証などを受付で提示してください。<br>
(If your birthday is in this same month, discount by JPY1,000. )<br>
レセプション時に誕生日の方には、一言ショート・スピーチをお願いしています。<br>
※懇親会では、お食事・お飲物をご用意しております。<br>
※「分野・国籍・年齢を超えてつながり、新しい発想で具体的に一歩踏み出してみよう！！」<br>
"We prepare refreshment in Networking-party."<br>
"Amalgamate different business area, nationalities, and ages... and one step forward!!"<br>
"That's one small step for man, one giant leap for mankind," (astronaut Neil Armstrong, July 20, 1969)<br>
"We prepare Halal foods for Muslim participants."<br>
------------------------------------------------------------------------------------------<br>
<br>
<%= simple_format(@event.note) %>

app/views/events/_form.html.erb
<h2><%= @title %></h2>

<p>* = <%= t('required') %></p>
<%= form_with model: @event do |f| %>
  <div class="row">
    <%= f.label :name, 'イベント名(*)', class: 'col-form-label col-sm-2' %>
    <%= f.text_field :name, class: "form-control col", :required => 'required' %>

    <%= f.label :cumulative_number, '通算#(*)', class: 'col-form-label col-sm-2' %>
    <%= f.text_field :cumulative_number, class: "form-control col", :required => 'required' %>
  </div>
  <div class="row">
    <%= f.label :start_time, '開始日時(*)', class: 'col-form-label col-sm-2' %>
    <div class="col">
      <%= f.datetime_select :start_time, {minute_step: 15, start_hour: 9} %>
    </div>

    <%= f.label :end_time, '終了日時(*)', class: 'col-form-label col-sm-2' %>
    <div class="col">
      <%= f.datetime_select :end_time, {discard_month: true, discard_year: true, minute_step: 15, start_hour: 11} %>
  </div>
  </div>
  <div class="row">
    <%= f.label :place_id, '会場(*)', class: 'col-form-label col-sm-2' %>
    <%= f.select :place_id, options_from_collection_for_select(Place.all, :id, :name, @event.place_id),
      { include_blank: 'Select a place' }, { class: "form-select col", required: true } %>

    <%= f.label :event_category_id, 'イベントタイプ(*)', class: 'col-form-label col-sm-2' %>
    <%= f.select :event_category_id, options_from_collection_for_select(EventCategory.all, :id, :name, @event.event_category_id),
      { include_blank: 'Select a event category' }, { class: "form-select col", required: true } %>
  </div>
  <div class="row">
    <%= f.label :fee, '参加費(*)', class: 'col-form-label col-sm-2' %>
    <%= f.number_field :fee, class: "form-control col", :value => 5000 %>
  </div>
  <div class="row">
    <%= f.label :fb_event_id, 'Facebook Event URL: ', class: 'form-label col-sm-2', for: "basic-url" %>
    <%= f.label :fb_event_id, 'https://www.facebook.com/events/', class: 'input-group-text col-auto', id: 'basic-addon3' %>
    <%= f.text_field :fb_event_id, class: "form-control col", id: "basic-url", 'aria-describedby': "basic-addon3" %>
  </div>
  <div class="row">
    <%= f.label :note, '備考', class: 'col-form-label col-sm-2' %>
    <%= f.text_area :note, class: "form-control col", rows: 10 %>
  </div>
  <div class="form-check form-switch">
    <%= f.check_box :is_public, class: "form-check-input col-auto", id: "flexSwitchCheckDefault" %>
    <%= f.label :is_public, '公開/Public', class: 'form-check-label', for: "flexSwitchCheckDefault" %>
  </div>

  <%= f.submit class: "btn btn-large btn-primary btn-block" %>
<% end %>

app/views/events/_side.html.erb
<div class="btn-group-vertical">
  <%= link_to 'イベント一覧', events_path, class: "btn btn-secondary" %>

  <div style='height: 4px;'></div>

  <% if params[:id].present? or params[:event_id].present? %>

    <%= link_to 'イベント情報', event_path(@event), class: "btn btn-secondary" %>
    <div style="height: 4px;"></div>
    <%= link_to "参加予定者リスト (#{@event.registed_members.count})", registed_event_path(@event), class: "btn btn-secondary" %>
    <%= link_to "出席者リスト (#{@event.participants.count})", participants_event_path(@event), class: "btn btn-secondary" %>
    <%= link_to "ドタ参リスト (#{@event.dotasan.count})", dotasan_event_path(@event), class: "btn btn-secondary" %>
    <%= link_to "欠席者リスト (#{@event.declined_members.count})", declined_event_path(@event), class: "btn btn-secondary" %>
    <%= link_to "ドタキャンリスト (#{@event.dotacan.count})", dotacan_event_path(@event), class: "btn btn-secondary" %>
    <%= link_to "No-showリスト (#{@event.no_show.count})", no_show_event_path(@event), class: "btn btn-secondary" %>
    <div style="height: 4px;"></div>
    <%= link_to "統計", statistics_event_path(@event), class: "btn btn-secondary" %>
    <div style="height: 4px;"></div>
    <%= link_to "会計", account_event_path(@event), class: "btn btn-secondary" %>

  <% else %>

    <%= link_to "イベント新規登録", new_event_path, class: "btn btn-secondary" %>
    <div style="height: 4px;"></div>
    <%= link_to "統計", statistics_events_path, class: "btn btn-secondary" %>
    <div style="height: 4px;"></div>
    <%= link_to "会場管理", places_path, class: "btn btn-secondary" %>
    <%= link_to "イベントタイプ管理", event_categories_path, class: "btn btn-secondary" %>
    <%= link_to "会計科目管理", accounts_path, class: "btn btn-secondary" %>
    <div style="height: 4px;"></div>
    <%= link_to "イベント情報Download", download_events_path(format: 'xls'), method: "get", class: "btn btn-secondary" %>

  <% end %>

  <% if request.path_info == "/events" %>
    <div class="well well-small">
      <ul class="list-unstyled">
        <li><%= "開催回数：#{@total_events}回" %></li>
        <li><%= "出席者延べ人数：#{@total_participants}名" %></li>
        <li><%= "出席者数：#{@participants}名" %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/events/declined.html.erb
<div class='container-fluid'>

  <div class="row">
    <div class="col-md-2" id="side-nav">
      <%= render'side' %>
    </div>

    <div class="col">
      <h2>欠席者一覧</h2>

      <div class="btn-group">
        <%= link_to declined_event_path, class: "btn btn-light" do %>
          <span class="fa fa-th-list"></span> 欠席者一覧
        <% end %>
      </div>

      <div id="ajax_container">
        <%= render 'members' %>
      </div>
    </div>
  </div>

</div>

app/views/events/dotasan.html.erb
<div class='container-fluid'>

  <div class="row">
    <div class="col-sm-2" id="side-nav">
      <%= render'side' %>
    </div>

    <div class="col">
      <h2>ドタ参リスト</h2>

      <div id="ajax_container">
        <%= render 'members' %>
      </div>
    </div>
  </div>

</div>

app/views/events/index.html.erb
<div class='container-fluid'>

  <div class="row">
    <aside class="col-md-2">
      <%= render'side' %>
    </aside>

    <div class="col">
      <h2>GTICイベント一覧</h2>

      <h3><%= "イベント検索" %></h3>
      <%= form_with url: search_events_path, method: 'get', data: { remote: true } do |form| %>
        <div class="row">
          <%= form.label :keyword, "Keyword: ", class: "col-form-label col-auto" %>
          <%= form.text_field :keyword, class: "form-control col", placeholder: "Keyword" %>
          <%= form.submit 'Search', class: 'btn btn-primary col-auto' %>
          <span class="form-text col-auto">アルファベットによる検索もOK（ひらがな、カタカナは未対応）</span>
        </div>
      <% end %>

      <!-- per year Paginate -->
      <% if @start_date.present? and @last_date.present? %>
        <div class="btn-group btn-group-sm">
          <% date = @last_date%>
          <% while date >= @start_date do %>
            <%= link_to "#{date.strftime("%Y")}年", events_path(year: date.strftime('%Y-%m-%d')), class: "btn btn-info" %>
            <% date = date - 1.year %>
          <% end %>
        </div>
      <% end %>

      <div id="ajax_container">
        <%= render 'events' %>
      </div>

    </div>
  </div>

</div>

app/views/events/registed.xls.erb
<%= render 'member_download' %>

app/views/events/search_member.js.erb
$("#ajax_container").html("<%= escape_javascript(render('add_member')) %>")

app/views/events/switch_black_list_flg.js.erb
$("#ajax_container").html("<%= escape_javascript(render('members')) %>")

app/views/events/update_birthday.js.erb
$("#ajax_container").html("<%= escape_javascript(render('members')) %>")

app/views/events/update_registed_member.js.erb
$("#ajax_container").html("<%= escape_javascript(render('members_form')) %>")