config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  #===================================================
  # Root path
  root 'static_pages#home'
  # Redirect root path
  #root to: redirect('/ja/home')


  #===================================================
  # Static pages
  match '/home', to: 'static_pages#home', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/ceo_message', to: 'static_pages#ceo_message', via: 'get'
  match '/organizer', to: 'static_pages#organizer', via: 'get'
  match '/media', to: 'static_pages#media', via: 'get'
  match '/search_media_article', to: 'static_pages#search_media_article', via: 'get'
  match '/our_sponsors', to: 'static_pages#our_sponsors', via: 'get'
  match '/contact_us', to: 'static_pages#contact_us', via: 'get'
  # Events
  match '/event_list', to: 'static_pages#event_list', via: 'get'
  match '/event_detail', to: 'static_pages#event_detail', via: 'get'
  match '/register_event_form', to: 'static_pages#register_event_form', via: 'post'
  match '/register_event_user', to: 'static_pages#register_event_user', via: 'post'
  match '/deregister_event', to: 'static_pages#deregister_event', via: 'post'
  match '/deregister_event_confirm', to: 'static_pages#deregister_event_confirm', via: 'get'


  #===================================================
  # For authentication
  devise_for :users, controllers: {
    #omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # User page
  resources :users do
    collection do
      get :privacy_policy
    end
  end


  #===================================================
  # Staff only

  # Prefix 'admin'
  # Uncommend and use if need for future
  # https://makandracards.com/makandra/38773-rails-route-namespacing-in-different-flavors
  #scope path: 'admin' do

    resources :accounts

    resources :broadcasts do
      collection do
        get 'sent_list'
      end
      member do
        get 'show_sent'
        get :find_members
        get :search
        get :send_email
        get :broadcast_member_list
        post :add_emails
        post :delete_broadcast_member
        post :update_include_all_flg
        post :update_broadcast_member
        post :update_birth_month
        post :update_event_id
        post :update_include_gtic_flg
      end
    end

    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :contacts do
      member do
        post 'update_response_completed'
      end
    end

    resources :events do
      collection do
        get :download
        get :search
        get :statistics
      end
      member do
        get :registed
        get :update_registed_member
        get :participants
        get :update_participants
        get :dotasan
        get :declined
        get :dotacan
        get :no_show
        get :waiting
        get :add_presenter
        get :add_as_presenter
        get :search_member
        get :statistics
        get :account
        get 'serve_file'
        get 'check_in'
        post :change_status
        post :change_role
        post :destroy_relationship
        post :switch_black_list_flg
        post :update_birthday
        post :create_member
        post 'upload_file'
        post 'set_bkg_image'
      end
    end

    resources :event_categories, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :images do
      collection do
        get :serve
      end
    end

    resources :media_articles do
      member do
        post :delete_file
        get :serve_file
      end
    end

    resources :members do
      collection do
        get :azsa_list
        get :no_show_list
        get :black_list
        get :category
        get :count
        get :search
        post :fill_alphabet_from_kanji_name
      end
      member do
        post 'upload_profile_picture'
      end
    end

    resources :places, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :presentations, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :relationships, only: [:create, :edit, :update, :destroy]
    resources :registers
    resources 'sponsors' do
      member do
        post 'upload_logo_image'
      end
    end
    resources :staffs

  #end # end of scope (prefix)

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_one :event
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :active_staff_only

  def index
    @places = Place.all
  end

  def new
    @title = "新規会場登録"
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to :places
    else
      render 'new'
    end
  end

  def show
    @place = Place.find(params[:id])
  end

  def edit
    @title = "会場情報修正"
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    if @place.update(place_params)
      redirect_to :places
    else
      render 'edit'
    end
  end


  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to :places
  end


  private
    def place_params
      params.require(:place).permit(
        :name, :address, :city, :nearest_station, :how_to_go,
        :latitude, :longitude
      )
    end

end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<h2><%= @title %></h2>

<p>*: <%= t('required') %></p>

<%= form_with model: @place do |form| %>
  <div class="form-group row">
    <%= form.label :name, '会場名(*)', class: 'col-form-label col-sm-2' %>
    <%= form.text_field :name, class: "form-control col", required: true %>
  </div>

  <div class="form-group row">
    <%= form.label :address, '住所', class: 'col-form-label col-sm-2' %>
    <%= form.text_field :address, class: "form-control col" %>
  </div>

  <div class="form-group row">
    <%= form.label :city, 'City', class: 'col-form-label col-sm-2' %>
    <%= form.text_field :city, class: "form-control col" %>

    <%= form.label :nearest_station, 'Nearest Station', class: 'col-form-label col-sm-2' %>
    <%= form.text_field :nearest_station, class: "form-control col" %>
  </div>

  <div class="form-group row">
    <%= form.label :latitude, 'Latitude（緯度）', class: 'col-form-label col-sm-2' %>
    <%= form.text_field :latitude, class: "form-control col" %>

    <%= form.label :longitude, 'Longitude（経度）', class: 'col-form-label col-sm-2' %>
    <%= form.text_field :longitude, class: "form-control col" %>
  </div>

  <div class="form-group row">
    <%= form.label :how_to_go, '行き方/How to go', class: 'col-form-label col-sm-2' %>
    <%= form.text_area :how_to_go, class: "form-control col", rows: 10 %>
  </div>


  <div class="form-group">
    <%= link_to "Back", places_path, class: "btn btn-info col-2" %>
    <%= form.submit "送信", class: "btn btn-primary col-2" %>
  </div>

<% end %>

app/views/places/edit.js.erb
$("#ajax_container").html("<%= escape_javascript(render('form')) %>")

app/views/places/index.html.erb
<div class='container-fluid'>

  <div class="row">
    <div class="col-sm-2">
      <%= render "events/side" %>
    </div>

    <div class="col">
      <div id="ajax_container">
        <h2>会場一覧</h2>

        <%= link_to "会場登録", new_place_path, method: :get, class: "btn btn-primary col-2", remote: true %>

        <table class="table table-bordered table-hover table-striped table-sm">
          <thead>
            <tr>
              <th>ID</th>
              <th>Created at</th>
              <th>会場名</th>
              <th>最寄り駅</th>
              <th>行き方</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @places.each do |place| %>
              <tr>
                <td><%= place.id %></td>
                <td><%= place.created_at.strftime('%Y-%m-%d') %></td>
                <td><%= place.name %></td>
                <td><%= place.nearest_station %></td>
                <td><%= truncate place.how_to_go, length: 20 %></td>
                <td>
                  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalPlace<%= place.id %>">
                    詳細
                  </button>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= link_to "会場登録", new_place_path, method: :get, class: "btn btn-primary col-2", remote: true %>
      </div>
    </div>
  </div>

</div>

<!-- Modal -->
<% @places.each do |place| %>
  <div class="modal fade" id="modalPlace<%= place.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><%= place.name %></h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <li>登録した日にち: <%= place.created_at.strftime('%Y-%m-%d') %></li>
          <li>Address: <%= place.address %></li>
          <li>City: <%= place.city %></li>
          <li>最寄り駅: <%= place.nearest_station %></li>
          <li>How to go: <%= place.how_to_go %></li>
          <iframe width="450" height="250" style="border:0" loading="lazy" allowfullscreen
                                                            src="https://www.google.com/maps/embed/v1/search?q=<%= place.latitude %>%2C<%= place.longitude %>&key=<%= ENV['GOOGLE_API_KEY'] %>">
          </iframe>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary " data-bs-dismiss="modal">Close</button>
          <%= link_to "編集", edit_place_path(place), class: 'btn btn-info', remote: true %>
          <%= link_to "削除", place_path(place), class: 'btn btn-danger',
              method: :delete, data: { confirm: "削除してもよろしいですか？"} %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/places/new.js.erb
$("#ajax_container").html("<%= escape_javascript(render('form')) %>")