config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  #===================================================
  # Root path
  root 'static_pages#home'
  # Redirect root path
  #root to: redirect('/ja/home')


  #===================================================
  # Static pages
  match '/home', to: 'static_pages#home', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/ceo_message', to: 'static_pages#ceo_message', via: 'get'
  match '/organizer', to: 'static_pages#organizer', via: 'get'
  match '/media', to: 'static_pages#media', via: 'get'
  match '/search_media_article', to: 'static_pages#search_media_article', via: 'get'
  match '/our_sponsors', to: 'static_pages#our_sponsors', via: 'get'
  match '/contact_us', to: 'static_pages#contact_us', via: 'get'
  # Events
  match '/event_list', to: 'static_pages#event_list', via: 'get'
  match '/event_detail', to: 'static_pages#event_detail', via: 'get'
  match '/register_event_form', to: 'static_pages#register_event_form', via: 'post'
  match '/register_event_user', to: 'static_pages#register_event_user', via: 'post'
  match '/deregister_event', to: 'static_pages#deregister_event', via: 'post'
  match '/deregister_event_confirm', to: 'static_pages#deregister_event_confirm', via: 'get'


  #===================================================
  # For authentication
  devise_for :users, controllers: {
    #omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # User page
  resources :users do
    collection do
      get :privacy_policy
    end
  end


  #===================================================
  # Staff only

  # Prefix 'admin'
  # Uncommend and use if need for future
  # https://makandracards.com/makandra/38773-rails-route-namespacing-in-different-flavors
  #scope path: 'admin' do

    resources :accounts

    resources :broadcasts do
      collection do
        get 'sent_list'
      end
      member do
        get 'show_sent'
        get :find_members
        get :search
        get :send_email
        get :broadcast_member_list
        post :add_emails
        post :delete_broadcast_member
        post :update_include_all_flg
        post :update_broadcast_member
        post :update_birth_month
        post :update_event_id
        post :update_include_gtic_flg
      end
    end

    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :contacts do
      member do
        post 'update_response_completed'
      end
    end

    resources :events do
      collection do
        get :download
        get :search
        get :statistics
      end
      member do
        get :registed
        get :update_registed_member
        get :participants
        get :update_participants
        get :dotasan
        get :declined
        get :dotacan
        get :no_show
        get :waiting
        get :add_presenter
        get :add_as_presenter
        get :search_member
        get :statistics
        get :account
        get 'serve_file'
        get 'check_in'
        post :change_status
        post :change_role
        post :destroy_relationship
        post :switch_black_list_flg
        post :update_birthday
        post :create_member
        post 'upload_file'
        post 'set_bkg_image'
      end
    end

    resources :event_categories, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :images do
      collection do
        get :serve
      end
    end

    resources :media_articles do
      member do
        post :delete_file
        get :serve_file
      end
    end

    resources :members do
      collection do
        get :azsa_list
        get :no_show_list
        get :black_list
        get :category
        get :count
        get :search
        post :fill_alphabet_from_kanji_name
      end
      member do
        post 'upload_profile_picture'
      end
    end

    resources :places, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :presentations, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :relationships, only: [:create, :edit, :update, :destroy]
    resources :registers
    resources 'sponsors' do
      member do
        post 'upload_logo_image'
      end
    end
    resources :staffs

  #end # end of scope (prefix)

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :registers, foreign_key: "account_iD", dependent: :destroy
  has_many :events, through: :registers, source: :event
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :active_staff_only

  def index
    @subtitle = ["収入科目","支出科目"]
    @accounts = Array.new(2)
    @accounts[0] = Account.where(positive: true)
    @accounts[1] = Account.where(positive: false)
  end

  def edit
    @title = "科目名変更"
    @account = Account.find(params[:id])
    @num = params[:num].to_i
    respond_to :js
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_params)
      redirect_to :accounts
    else
      render 'edit'
    end
  end

  def new
    @title = "会計科目登録"
    @num = params[:num].to_i
    if @num == 0
      @account = Account.new(positive: true)
    else
      @account = Account.new(positive: false)
    end
    respond_to :js
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to :accounts
    else
      render 'new'
    end
  end


  def destroy
    account = Account.find(params[:id])
    account.destroy
    redirect_to :accounts
  end

#--------
  private
#--------
  def account_params
    params.require(:account).permit(:title, :positive)
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<h2><%= @title %></h2>
<%= form_for @account, :html => { :class => 'form-horizontal center' } do |f| %>
  <%= f.hidden_field :positive %>
  <table class="table" >
    <tr>
      <th class="col-lg-2">科目名</th>
      <th class="col-lg-1"></th>
      <th class="col-lg-1"></th>
    </tr>
    <tr>
      <td><%= f.text_field :title, class: "form-control" %></td>
      <td><%= submit_tag "送信", class: "btn btn-primary btn-sm" %></td>
      <td><%= link_to "キャンセル", accounts_path, class: "btn btn-light btn-sm" %></td>
    </tr>
  </table>
<% end %>

app/views/accounts/edit.js.erb
<% if @num == 0 %>
  $("#ajax-container-0").html("<%= escape_javascript(render("form")) %>");
<% else %>
  $("#ajax-container-1").html("<%= escape_javascript(render("form")) %>");
<% end %>

app/views/accounts/index.html.erb
<div class='container-fluid'>

  <div class="row">
    <aside class="col-sm-2">
      <%= render "events/side" %>
    </aside>

    <% 2.times do |i| %>
      <div class="col-sm-5">
        <div id="ajax-container-<%= i %>">
          <h2><%= @subtitle[i] %></h2>
          <table class="table">
            <tr>
              <th class="col-lg-2">科目名</th>
              <th class="col-lg-1"></th>
              <th class="col-lg-1"></th>
            </tr>
            <% @accounts[i].each do |account| %>
              <tr>
                <td><%= account.title %></td>
                <td><%= link_to "編集", edit_account_path(account, num: i), remote: true %> </td>
                <td><%= link_to "削除", account_path(account), method: :delete %> </td>
              </tr>
            <% end %>
          </table>
          <%= link_to "科目登録", new_account_path(num: i), method: :get, class: "btn btn-primary btn-block", remote: true %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/accounts/new.js.erb
<% if @num == 0 %>
  $("#ajax-container-0").html("<%= escape_javascript(render"form") %>");
<% else %>
  $("#ajax-container-1").html("<%= escape_javascript(render"form") %>");
<% end %>